### ISSUE TITLE
issue with locale (wrong [log] output)

### ISSUE THREAD

**Issue by k-a-z-u** [charonn0/HTTPTestGenerator#7]
In the log, I get outputs like:

POST / HTTP/**11,0**
and
HTTP/**11,0** 400 Bad Request

I guess this is due to the german local the program is running with: issue with "," and "." for numbers.
Unfortunately I do not know whether this concerns only the log or even the sent packets.

**Comment by charonn0** [comment]
This appears to be the result of using the `Format` library method, which respects the user's locale when formatting numbers with a decimal point. This is done for both [requests](https://github.com/charonn0/HTTPTestGenerator/blob/master/HTTP/Request.rbbas#L130) and [responses](https://github.com/charonn0/HTTPTestGenerator/blob/master/HTTP/Response.rbbas#L63). Moreover, the `CDbl` method is used to reverse the process, and it also uses the user's locale to determine the decimal point character. Shouldn't be hard to fix.

**Comment by charonn0** [comment]
Please try installing the latest version. You can download the installer from the [project page](http://www.boredomsoft.org/http-request-generator.bs).

**Comment by charonn0** [comment]
> I do not know whether this concerns only the log or even the sent packets.

This would affect both the log and the packets, and is probably why you were receiving a `400 Bad Request` response from the server.
